name: nixtla
channels:
  - conda-forge
dependencies:
  - dask
  - dask-expr<1.0.12
  - jupyterlab
  - pandas<2.2
  - plotly
  - pyspark>=3.3
  - pip:
    - black
    - holidays
    - nbdev
    - mypy
    - flake8
    - python-dotenv
    - statsforecast
    - utilsforecast>=0.0.13
    - requests
    - fugue[ray]>=0.8.7
    - ray[serve-grpc]<2.6.3
    - fire
    - tabulate
    - tenacity
