name: Deploy to readme dot com

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-readme:
    runs-on: ubuntu-latest
    env:
      readme_version: "0.0.2"
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # 5.3.0
        with:
          python-version: "3.10"

      - name: Install pip requirements
        run: pip install ".[dev]"

      - name: Install Quarto
        run: nbdev_install_quarto

      - name: Create readme docs
        env:
          README_HOST_URL: ${{ secrets.README_HOST_URL }}
          README_CATEGORY: ${{ secrets.README_CATEGORY }}
          README_API_KEY: ${{ secrets.README_API_KEY }}
          README_VERSION: ${{ env.readme_version }}
        run: ./action_files/readme_com/create_readme_docs.sh

      - name: Push PNGs to readme_docs branch
        run: |
          git config --global user.name 'FedericoGarza'
          git config --global user.email 'fede.garza.ramirez@gmail.com'
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }} --delete readme_docs || true
          git checkout -b readme_docs
          git add -f "*.png"
          git commit -m "[cd] update png images" || echo "No changes to commit"
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }} HEAD:readme_docs

      - name: Deploy to readme com
        uses: readmeio/rdme@51a80867c45de15e2b41af0c4bd5bbc61b932804 # 8.6.6
        with:
          rdme: docs ./nbs/_docs/docs/ --key=${{ secrets.README_API_KEY }} --version=${{ env.readme_version }}
